name: CI pipe

# Run this workflow every time a new pull request is created
on: pull_request

jobs:
  test-and-build:
    name: Test and build echo server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go env
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15.5"

      - name: Run tests
        run: go test -v

      - name: Build
        run: go build
